export const words = [
  "graphic design",
  "web design",
  "logo design",
  "UI/UX design",
  "branding",
  "illustration",
  "typography",
  "motion graphics",
  "packaging design",
  "print design",
  "product design",
  "interior design",
  "fashion design",
  "industrial design",
  "game design",
  "user interface design",
  "art direction",
  "photography",
  "architecture",
  "industrial engineering",
  "visual identity",
  "creative direction",
  "animation",
  "digital art",
  "user experience",
  "3D modeling",
  "advertising",
  "concept art",
  "film production",
  "fine arts",
  "interaction design",
  "mobile app design",
  "virtual reality",
  "brand identity",
  "social media design",
  "urban design",
  "textile design",
  "video editing",
  "responsive design",
  "street art",
  "game development",
  "sketching",
  "e-commerce design",
  "wayfinding design",
  "data visualization",
  "music production",
  "comic art",
  "infographic design",
  "book design",
  "AR/VR design",
  "digital marketing",
  "packaging production",
  "post-production",
  "concept design",
  "computer-aided design (CAD)",
  "illustrative art",
  "design management",
  "set design",
  "UI prototyping",
  "brand strategy",
  "artificial intelligence design",
  "bio-design",
  "experimental design",
  "emerging technologies",
  "inclusive design",
  "game art",
  "experience design",
  "visual storytelling",
  "environmental design",
  "information architecture",
  "wearable technology",
  "data-driven design",
  "design thinking",
  "creative coding",
  "augmented reality",
  "service design",
  "interface design",
  "creative strategy",
  "inclusive design",
  "design ethics",
  "design research",
  "interactive media",
  "digital illustration",
  "sound design",
  "design for social impact",
  "design for sustainability",
  "data analysis and visualization",
  "experimental typography",
  "design systems",
  "behavioral design",
  "voice user interface (VUI) design",
  "motion design",
  "experiential design",
  "human-centered design",
  "game narrative design",
  "design leadership",
  "multi-disciplinary design",
  "design education",
  "motion design",
  "visual design",
  "3D modeling",
  "rendering",
  "game design",
  "virtual reality design",
  "augmented reality design",
  "user experience (UX) design",
  "user interface (UI) design",
  "design research",
  "design thinking",
  "design strategy",
  "design management",
  "design leadership",
  "design methodologies",
  "design systems",
  "user-centered design",
  "human-computer interaction (HCI)",
  "digital design",
  "print design",
  "brand strategy",
  "brand identity",
  "creative direction",
  "storyboarding",
  "motion capture",
  "data visualization design",
  "interactive media design",
  "web development",
  "front-end development",
  "back-end development",
  "user experience optimization",
  "information design",
  "game development",
  "experience design",
  "service design",
  "industrial design",
  "architectural design",
  "design education",
  "design workshops",
  "design mentorship",
  "artificial intelligence in design",
  "machine learning in design",
  "ethics in design",
  "inclusive design",
  "design for accessibility",
  "sustainable design",
  "emerging technologies in design",
  "design for social impact",
  "cultural sensitivity in design",
  "design thinking for innovation",
  "design for behavior change",
  "design for wellbeing",
  "design for environmental impact",
  "design for future generations",
  "data-driven design",
  "adaptive design",
  "multi-disciplinary design",
  "cross-cultural design",
  "experimental design",
  "design history and theory",
  "design criticism",
  "design anthropology",
  "design entrepreneurship",
  "design in marketing",
  "design in advertising",
  "design in business",
  "design in technology",
  "design in healthcare",
  "design in education",
  "design in entertainment",
  "design in social media",
  "design in fashion",
  "design in architecture",
  "design in gaming",
  "design in journalism",
  "design in music",
  "design in sports",
  "design in travel",
  "design in food industry",
  "design in automotive industry",
  "Art guides creativity.",
  "Brand identity creation.",
  "Conceptual visual representation.",
  "Data visualization clarity.",
  "Environmental space creation.",
  "Fashion trend innovation.",
  "Game development collaboration.",
  "Human-centered product design.",
  "Illustration storytelling enhancement.",
  "Journalism engaging formats.",
  "Typography message conveyance.",
  "Logo essence encapsulation.",
  "Motion graphics engagement.",
  "Narrative game experiences.",
  "Outdoor advertising strategies.",
  "Product design fusion.",
  "Quality design excellence.",
  "Responsive user experiences.",
  "Service optimization touchpoints.",
  "Textile unique fabrics.",
  "User interface interaction.",
  "Visual narrative communication.",
  "Wearable tech merging.",
  "eXperiential immersive environments.",
  "YouTube graphic attraction.",
  "Zealous design distinction.",
];
